### PR TITLE
Added Interploation Search

### PR DESCRIPTION
**Pull request by gaurang7goel**
#3 Issue
@4N1Z  please check.

### CODE REVIEW

**Review by AnirudhDaya — COMMENTED** [review]
Hey pal, <conio.h> is not a part of the standard C library. Moreover, I don't think your code requires <conio.h> header file to run. Please make the necessary corrections. Also, try and include the time complexity and space complexity of the algorithm.

**Comment by gaurang7goel** [comment]
@4N1Z @AnirudhDaya  Done changes please check.

**Review by AnirudhDaya — CHANGES_REQUESTED** [review]
Hey, great work buddy. One last suggestion I would give is to remove the macro of 'MAX' and declare the array 'arr' after receiving the input of 'num'. This reduces the wastage of space.

```c
	int i, num;
	int item, pos;

	printf("\nEnter total elements: ");
	scanf("%d", &num);
        int arr[num]
```

**Comment by gaurang7goel** [comment]
Sure, sir

**Comment by gaurang7goel** [comment]
@AnirudhDaya @4N1Z  Done  SIr, please check

**Review by AnirudhDaya — APPROVED** [review]
Great work buddy! Merging this one.

**Comment by gaurang7goel** [comment]
Thank you sir

**Pull request merged**
