### PR TITLE
Bucket sort in_python

### PR DESCRIPTION
**Pull request by rishavupraity**
Added Sorting->Bucket-sort->in_python.py

### CODE REVIEW

**Comment by AnirudhDaya** [comment]
Hey buddy duplicate DFS. remove that

**Comment by rishavupraity** [comment]
Ok @AnirudhDaya  removed

**Review by 4N1Z — CHANGES_REQUESTED** [review]
Hey Pal,
Great code and thank you for your contributions.
Need Change :

- Add documentation for your code as comments inside the code itself.
- - Include time and space complexities .

Happy coding !

**Comment by rishavupraity** [comment]
> Hey Pal, Great code and thank you for your contributions. Need Change :
> 
> * Add documentation for your code as comments inside the code itself.
> * * Include time and space complexities .
> 
> Happy coding !

Thank you
Documentation Added

**Review by 4N1Z — APPROVED** [review]

**Pull request merged**
