### PR TITLE
Added Sorting Algorithm (Bogo Sort)

### PR DESCRIPTION
**Pull request by AryaDeepanshu**
Bogosort (also known as permutation sort, stupid sort, or slowsort) is a sorting algorithm 
based on the generate and test paradigm. The function successively generates permutations 
of its input  until it finds one that is sorted. It is not considered useful for sorting, 
but may be used for educational purposes, to contrast it with more efficient algorithms.

### CODE REVIEW

**Review by gaurang7goel — APPROVED** [review]

**Comment by AryaDeepanshu** [comment]
#4   issue
@AnirudhDaya @4N1Z  verify the PR

**Review by AnirudhDaya — CHANGES_REQUESTED** [review]
Hey pal, the code works great. But needs documentation like 
-  Complexities

**Comment by AryaDeepanshu** [comment]
> Hey pal, the code works great. But needs documentation like
> 
> * Complexities

requested changes are made

**Review by AnirudhDaya — APPROVED** [review]
Great work buddy! Merging this one.

**Pull request merged**
