### PR TITLE
Added the Jump Search program in javascript

### PR DESCRIPTION
**Pull request by manojrayar**
Hello, Added the Jump search program in Javascript language.

### CODE REVIEW

**Review by AnirudhDaya — CHANGES_REQUESTED** [review]
Hey pal, the code works great. But needs documentation like 
-- Explanation on what jump search is
-- Complexities

**Comment by manojrayar** [comment]
Hello, 
Updated the documentation and the complexity info. 
please do check and merge.

**Comment by 4N1Z** [comment]
@AnirudhDaya Review this code .

**Comment by manojrayar** [comment]
Hello, @AnirudhDaya . please do review and merge it.

**Comment by AnirudhDaya** [comment]
Hey pal, this code already exists in our repo.

**Pull request closed without merging**
