### PR TITLE
pancake sorting

### PR DESCRIPTION
**Pull request by PranjalSK03**
sorting array with minimum possible reversals.

### CODE REVIEW

**Comment by PranjalSK03** [comment]
the sorting is called is pancake sorting. please lool into it.

**Review by AnirudhDaya — APPROVED** [review]
Hey pal, the code works great. But needs documentation like 
-- Explanation of what pancake sort is
-- Complexities

**Review by PranjalSK03 — COMMENTED** [review]
sir, i made the new changes as asked for in the sorting algo.

**Comment by PranjalSK03** [comment]
please confirm if i should add any more.

**Comment by PranjalSK03** [comment]
sir, when will this be merged ?

**Review by AnirudhDaya — APPROVED** [review]
Great work buddy! Merging this one.

**Comment by PranjalSK03** [comment]
thank you sir for your attention.

**Pull request merged**
