### PR TITLE
Create QuickSort.java

### PR DESCRIPTION
**Pull request by ayusshrathore**

### CODE REVIEW

**Review by AnirudhDaya — CHANGES_REQUESTED** [review]
Great code. But do add the explanation of the algorithm as well the time and space complexities

**Comment by ayusshrathore** [comment]
Hey mate,

Thanks for reviewing the code and pointing out things. I've added the explanation and complexities for the algorithm. Do have a look and let me know if something's missing.

Happy merging :)

**Comment by ayusshrathore** [comment]
Hey mate,

I closed the pull request by mistake, kindly review the changes and merge accordingly.

**Review by ayusshrathore — COMMENTED** [review]
Hey mate,

Thanks for reviewing the code and pointing out things. I've added the explanation and complexities for the algorithm. Do have a look and let me know if something's missing.

Happy merging :)

**Review by AnirudhDaya — APPROVED** [review]
Great work buddy! Merging this one.

**Pull request merged**
