### PR TITLE
mergesort in java

### PR DESCRIPTION
**Pull request by ruchikayadav1408**
Please check merge sort in java

### CODE REVIEW

**Review by 4N1Z — CHANGES_REQUESTED** [review]
Hey Pal,
Glad to see your contribution 😄
Points to change :
- Change the name of the file from 'mergesort.java' to 'in_Java.java'.
- Add the details of Merge sort as documentation inside the code itself
-The details should include :
-- What is merge sort ? (or How it works)
-- Time and space complexity.

**Comment by ruchikayadav1408** [comment]
> * in_Java.java

updated all the changes!! please check it

**Comment by ruchikayadav1408** [comment]
please check countsort

**Comment by ruchikayadav1408** [comment]
> Hey, great merge sort code but the counting sort code lacks some documentation like explanations and complexities.

heyy, please check it, I did all the changes.

**Comment by ruchikayadav1408** [comment]
> > Hey, great merge sort code but the counting sort code lacks some documentation like explanations and complexities.
> 
> heyy, please check it, I did all the changes.

Can you please merge it and add label hacktoberfest

**Pull request merged**
