### PR TITLE
Create Exponential search in c++

### PR DESCRIPTION
**Pull request by shardendu930**
Added exponential search in c++ language

### CODE REVIEW

**Review by 4N1Z — CHANGES_REQUESTED** [review]
Hey Pal,
Thankyou for your contribution.
Changes :

- Check your code.
- Change the name of the code inside the file to in cpp.c++
- Add documentation as comments inside the file itself.
- - must contain : Time and space complexity .

Happy coding !

**Comment by shardendu930** [comment]
Thanks for appreciating. I will change it by today itself.

**Comment by shardendu930** [comment]
I have made all the suggested changes please review and merge it @AnirudhDaya

**Comment by shardendu930** [comment]
I have made changes as per suggestions . Please review and accept my pr @AnirudhDaya #55

**Comment by shardendu930** [comment]
Hii @4N1Z/Sorting-Searching-Algorithms
***@***.***>  I have
made changes 2 days ago as per your request. Please review and merge my pr
by today.

**Pull request merged**
