### PR TITLE
Create in_Python.py

### PR DESCRIPTION
**Pull request by shardendu930**
Added shell short.

### CODE REVIEW

**Comment by shardendu930** [comment]
Hii @AnirudhDaya please review my pr .

**Review by 4N1Z — CHANGES_REQUESTED** [review]
Hey Pal,
Great code and thank you for your contributions.
Need Change :

- Create a folder for shell sort and place the code inside it .

Happy coding !

**Comment by shardendu930** [comment]
Okay @4N1Z  I will create a folder for shell short and place the code inside it by today itself.

**Comment by shardendu930** [comment]
Please check @4N1Z I have created a folder named shell short and pushed the code inside it.

**Review by 4N1Z — APPROVED** [review]

**Comment by 4N1Z** [comment]
Add the code again in the correct location.

**Pull request merged**
