### PR TITLE
Create in_CPP.cpp

### PR DESCRIPTION
**Pull request by shardendu930**
Added interpolation search in cpp

### CODE REVIEW

**Comment by shardendu930** [comment]
Hii @4N1Z I have added interpolation search in cpp. Please review my pr and merge it.

**Comment by shardendu930** [comment]
@AnirudhDaya  please review and merge my pr as soon as possible.

**Review by AnirudhDaya — CHANGES_REQUESTED** [review]
Hey, buddy put it in the appropriate folder.

**Comment by shardendu930** [comment]
@AnirudhDaya I have changed the folder name to Interpolation search.

**Comment by shardendu930** [comment]
@AnirudhDaya please review my changed pr and merge it by today.

**Comment by shardendu930** [comment]
Hii @4N1Z/Sorting-Searching-Algorithms
***@***.***>  I have
made changes 2 days ago as per your request. Please review and merge my pr
by today.

**Comment by AnirudhDaya** [comment]
Buddy, stop tagging us. We will merge it when we do get time. Maintainers are not paying attention to their repo 24/7. Hope you get it pal.

**Comment by AnirudhDaya** [comment]
If the folder already exists please add into it, do not create a new one.

**Comment by shardendu930** [comment]
I have make changes as per your requirement please review and merge my pr by today.

**Comment by shardendu930** [comment]
I have added it on the existing interpolation search folder. Please check
it and merge my pr by today.

**Comment by shardendu930** [comment]
Please merge my pr by today because I only need one more pr approval to complete my 4 pr in hactoberfest and it takes 7 days for approval. So please  review and merge my pr.

**Comment by shardendu930** [comment]
Please merge my pr it will be too late.

**Review by AnirudhDaya — APPROVED** [review]
Great work buddy! Merging this one.

**Pull request merged**
