### PR TITLE
Contribute bucket sort algorithm in java

### PR DESCRIPTION
**Pull request by aaaravv**

### CODE REVIEW

**Review by 4N1Z — CHANGES_REQUESTED** [review]
Hey Pal,
Glad to see your contribution 😄
Points to change :
- remove the Main.class file.
- rename the file 'bucket_sort_java.java' to 'in_Java.java', and make adjusting.
- Add the details of Bucket Search as documentation
- The details should include :
- - What is bucket Search?
- - Time and space complexity 

Happy Coding !

**Comment by aaaravv** [comment]
Hey Pal,
I'm delighted you reached out to me & pointed out the mistake also I carried out the necessary changes, I hope you appreciate them.

Happy merging! ;)

**Review by aaaravv — COMMENTED** [review]
Hey Pal,
I'm delighted you reached out to me & pointed out the mistake also I carried out the necessary changes, I hope you appreciate them.

Happy merging! ;)

**Review by AnirudhDaya — APPROVED** [review]
Great work buddy! Merging this one.

**Review by 4N1Z — COMMENTED** [review]
Happy Coding !

**Comment by aaaravv** [comment]
Great dude appreciate it!

Happy October!!!

**Pull request merged**
