### PR TITLE
feat: Added bubble sort changes in cpp

### PR DESCRIPTION
**Pull request by SrigiriSruthi**

### CODE REVIEW

**Comment by SrigiriSruthi** [comment]
@4N1Z i ahve raised a pull request. Can u please review it?

**Comment by AnirudhDaya** [comment]
Hey pal, this code already exists in our repo.

**Comment by SrigiriSruthi** [comment]
ohk sure!

**Comment by SrigiriSruthi** [comment]
@AnirudhDaya can u assign me anycother task?

**Pull request closed without merging**
